BitmapFont: 64 547 48 16 8
BDFRefChar: 106 270 0 0 N
BDFRefChar: 165 541 0 3 N
BDFRefChar: 165 70 0 0 N
BDFRefChar: 166 542 -3 3 N
BDFRefChar: 166 70 0 0 N
BDFRefChar: 167 70 0 0 N
BDFRefChar: 168 540 0 7 N
BDFRefChar: 168 70 0 0 N
BDFRefChar: 169 541 -1 3 N
BDFRefChar: 169 74 0 0 N
BDFRefChar: 170 542 -4 3 N
BDFRefChar: 170 74 0 0 N
BDFRefChar: 171 74 0 0 N
BDFRefChar: 172 540 -1 7 N
BDFRefChar: 172 74 0 0 N
BDFRefChar: 175 541 -1 3 N
BDFRefChar: 175 80 0 0 N
BDFRefChar: 176 542 -4 3 N
BDFRefChar: 176 80 0 0 N
BDFRefChar: 177 80 0 0 N
BDFRefChar: 178 80 0 0 N
BDFRefChar: 179 540 -1 7 N
BDFRefChar: 179 80 0 0 N
BDFRefChar: 182 541 -1 3 N
BDFRefChar: 182 86 0 0 N
BDFRefChar: 183 542 -4 3 N
BDFRefChar: 183 86 0 0 N
BDFRefChar: 184 86 0 0 N
BDFRefChar: 185 540 -1 7 N
BDFRefChar: 185 86 0 0 N
BDFRefChar: 189 541 0 -9 N
BDFRefChar: 189 98 0 0 N
BDFRefChar: 190 542 -3 -9 N
BDFRefChar: 190 98 0 0 N
BDFRefChar: 191 98 0 0 N
BDFRefChar: 192 98 0 0 N
BDFRefChar: 193 540 0 -5 N
BDFRefChar: 193 98 0 0 N
BDFRefChar: 197 541 0 -9 N
BDFRefChar: 197 102 0 0 N
BDFRefChar: 198 542 -3 -9 N
BDFRefChar: 198 102 0 0 N
BDFRefChar: 199 102 0 0 N
BDFRefChar: 200 540 0 -5 N
BDFRefChar: 200 102 0 0 N
BDFRefChar: 201 541 0 -13 N
BDFRefChar: 201 270 0 0 N
BDFRefChar: 202 542 -3 -13 N
BDFRefChar: 202 270 0 0 N
BDFRefChar: 203 270 0 0 N
BDFRefChar: 204 540 0 -9 N
BDFRefChar: 204 270 0 0 N
BDFRefChar: 207 541 0 -9 N
BDFRefChar: 207 112 0 0 N
BDFRefChar: 208 542 -3 -9 N
BDFRefChar: 208 112 0 0 N
BDFRefChar: 209 112 0 0 N
BDFRefChar: 210 112 0 0 N
BDFRefChar: 211 540 0 -5 N
BDFRefChar: 211 112 0 0 N
BDFRefChar: 214 541 -1 -9 N
BDFRefChar: 214 118 0 0 N
BDFRefChar: 215 542 -4 -9 N
BDFRefChar: 215 118 0 0 N
BDFRefChar: 216 118 0 0 N
BDFRefChar: 217 540 -1 -5 N
BDFRefChar: 217 118 0 0 N
BDFRefChar: 218 542 -4 -9 N
BDFRefChar: 218 122 0 0 N
BDFRefChar: 261 74 0 0 N
BDFRefChar: 262 270 0 0 N
EndBitmapFont
