SplineFontDB: 3.2
FontName: myfont
FullName: myfont
FamilyName: myfont
Weight: Medium
Copyright: 
Version: 1.0
ItalicAngle: 0
UnderlinePosition: -150
UnderlineWidth: 100
Ascent: 4800
Descent: 1600
InvalidEm: 0
sfntRevision: 0x00010000
LayerCount: 2
Layer: 0 1 "Back" 1
Layer: 1 1 "Fore" 0
XUID: [1021 80 -2096353482 8731451]
StyleMap: 0x0040
FSType: 0
OS2Version: 5
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1786342554
ModificationTime: 1786467672
PfmFamily: 17
TTFWeight: 500
TTFWidth: 5
LineGap: 0
VLineGap: 0
Panose: 2 0 0 9 0 0 0 0 0 0
OS2TypoAscent: 4800
OS2TypoAOffset: 0
OS2TypoDescent: -1600
OS2TypoDOffset: 0
OS2TypoLinegap: 0
OS2WinAscent: 4800
OS2WinAOffset: 0
OS2WinDescent: 1600
OS2WinDOffset: 0
HheadAscent: 4800
HheadAOffset: 0
HheadDescent: -1600
HheadDOffset: 0
OS2SubXSize: 6400
OS2SubYSize: 6400
OS2SubXOff: 0
OS2SubYOff: 3200
OS2SupXSize: 6400
OS2SupYSize: 6400
OS2SupXOff: 0
OS2SupYOff: 3200
OS2StrikeYSize: 100
OS2StrikeYPos: 2400
OS2CapHeight: 4000
OS2XHeight: 2800
OS2Vendor: 'KBnP'
OS2CodePages: 00000000.80d40000
OS2UnicodeRanges: a00000af.000079eb.00000020.00000000
Lookup: 260 0 0 "diacritical" { "default top and bottom"  } ['mark' ('DFLT' <'dflt' > 'grek' <'dflt' > 'latn' <'dflt' > ) ]
MarkAttachClasses: 1
DEI: 91125
ShortTable: maxp 16
  1
  0
  543
  288
  72
  0
  0
  2
  0
  0
  0
  0
  0
  0
  0
  0
EndShort
LangName: 1033 "" "" "Regular" "BitsNPicas: myfont: 2026" "" "Version 1.0" "" "" "Made with Bits'n'Picas by Kreative Software" "" "" "http://www.kreativekorp.com/software/bitsnpicas/"
Encoding: UnicodeBmp
Compacted: 1
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -72
AntiAlias: 1
FitToEm: 0
WinInfo: 72 8 5
BeginPrivate: 0
EndPrivate
AnchorClass2: "bottom" "default top and bottom" "top" "default top and bottom"
EndSplineFont
