BitmapFont: 64 600 48 16 8
BDFRefChar: 161 65 0 0 N
BDFRefChar: 186 89 0 0 N
BDFRefChar: 221 65 0 0 N
BDFRefChar: 222 97 0 0 N
BDFRefChar: 239 69 0 0 N
BDFRefChar: 240 101 0 0 N
BDFRefChar: 261 73 0 0 N
BDFRefChar: 262 270 0 0 N
BDFRefChar: 263 73 0 0 N
BDFRefChar: 264 270 0 0 N
BDFRefChar: 271 74 0 0 N
BDFRefChar: 276 76 0 0 N
BDFRefChar: 277 108 0 0 N
BDFRefChar: 547 79 0 0 N
BDFRefChar: 549 85 0 0 N
BDFRefChar: 558 107 0 0 N
EndBitmapFont
