BitmapFont: 64 596 48 16 8
BDFRefChar: 159 65 0 0 N
BDFRefChar: 160 65 0 0 N
BDFRefChar: 167 69 0 0 N
BDFRefChar: 171 73 0 0 N
BDFRefChar: 174 78 0 0 N
BDFRefChar: 177 79 0 0 N
BDFRefChar: 178 79 0 0 N
BDFRefChar: 184 85 0 0 N
BDFRefChar: 191 97 0 0 N
BDFRefChar: 192 97 0 0 N
BDFRefChar: 199 101 0 0 N
BDFRefChar: 203 270 0 0 N
BDFRefChar: 206 110 0 0 N
BDFRefChar: 209 111 0 0 N
BDFRefChar: 210 111 0 0 N
BDFRefChar: 216 117 0 0 N
BDFRefChar: 227 67 0 0 N
BDFRefChar: 228 99 0 0 N
BDFRefChar: 229 67 0 0 N
BDFRefChar: 230 99 0 0 N
BDFRefChar: 233 67 0 0 N
BDFRefChar: 234 99 0 0 N
BDFRefChar: 235 68 0 0 N
BDFRefChar: 247 69 0 0 N
BDFRefChar: 248 101 0 0 N
BDFRefChar: 257 72 0 0 N
BDFRefChar: 258 104 0 0 N
BDFRefChar: 286 78 0 0 N
BDFRefChar: 287 110 0 0 N
BDFRefChar: 290 78 0 0 N
BDFRefChar: 291 110 0 0 N
BDFRefChar: 302 82 0 0 N
BDFRefChar: 303 114 0 0 N
BDFRefChar: 306 82 0 0 N
BDFRefChar: 307 114 0 0 N
BDFRefChar: 314 83 0 0 N
BDFRefChar: 315 115 0 0 N
BDFRefChar: 318 84 0 0 N
BDFRefChar: 543 65 0 0 N
BDFRefChar: 544 97 0 0 N
BDFRefChar: 545 73 0 0 N
BDFRefChar: 546 270 0 0 N
BDFRefChar: 548 111 0 0 N
BDFRefChar: 550 117 0 0 N
BDFRefChar: 552 217 0 0 N
BDFRefChar: 555 71 0 0 N
BDFRefChar: 556 103 0 0 N
BDFRefChar: 557 75 0 0 N
BDFRefChar: 558 107 0 0 N
BDFRefChar: 562 72 0 0 N
BDFRefChar: 563 104 0 0 N
EndBitmapFont
